INSERT INTO AUTO (AUTO_ID, ANIO, MARCA, MODELO)
VALUES (1, 2015, 'Nissan', 'G87');

INSERT INTO OFICINA_UBER (OFICINA_UBER_ID, CIUDAD, PAIS, UBICACION)
VALUES (1, 'Osorno', 'Chile', 'Las Tórtolas 156');
INSERT INTO OFICINA_UBER (OFICINA_UBER_ID, CIUDAD, PAIS, UBICACION)
VALUES (2, 'Temuco', 'Chile', 'Gabriela Mistral 785');
INSERT INTO OFICINA_UBER (OFICINA_UBER_ID, CIUDAD, PAIS, UBICACION)
VALUES (3, 'Santiago', 'Chile', 'Balmaceda 4115');

INSERT INTO CHOFER (CHOFER_ID, NOMBRE, RATING, AUTO_ID, OFICINA_UBER_ID)
VALUES (1, 'Eduardo Gatica', 9, 1, 1);

ALTER SEQUENCE HIBERNATE_SEQUENCE INCREMENT BY 5;
SELECT HIBERNATE_SEQUENCE.nextval FROM DUAL;
ALTER SEQUENCE HIBERNATE_SEQUENCE INCREMENT BY 1;
